libbpf/bpftool

.github/workflows/build.yaml
src/Makefile.feature

Feature detection for libbfd is not passed down correctly to the main Makefile, leaving the disassembler for JIT-ed programs always compiled out. Fix `$(feature-libbfd)` and derivatives, and add a quick check with `bpftool version` to the CI workflow.

Fix feature detection for libbfd, add related CI check after buildling bpftool

---

.github/workflows/build.yaml
include/linux/compiler.h
src/Makefile.feature
src/Makefile.include

This should address the two issues raised in #3: `clang` erroring out of features detection because of warnings produced by unnecessary flags passed to the linker, and a portability issue related to the use of `echo` to print text including line breaks.
In another commit, fix the usage of `$(LLVM_VERSION)` in Makefile.include.
The last commits add a new CI build, this time relying on clang to build bpftool, and fix a header so that this build can succeed.

Fix features detection: clang and portability

---

include/uapi/linux/if_link.h
scripts/sync-kernel.sh

Copy tools/include/uapi/linux/if_link.h from kernel's repository, taken at the current checkpoint. We want this header in the repo so we can be sure that it contains the flags `XDP_ATTACHED_MULTI` and `IFLA_XDP_PROG_ID`, used in netlink_dumper.c.

Ship linux/if_link.h UAPI header

---

include/uapi/linux/netlink.h
scripts/sync-kernel.sh

Copy `tools/include/uapi/linux/netlink.h` from kernel's repository, taken at commit dc37dc617fab ("libbpf: Fix compilation warning due to mismatched printf format") (current checkpoint).
We want this header in the repo so we can be sure that it contains the flags `NETLINK_EXT_ACK`, used in `net.c`.
Fixes: #10

mirror: Ship linux/netlink.h UAPI header

---

src/Makefile.feature

When attempting to strengthen libbfd feature detection in Makefile.feature, the fix was not applied properly to `feature-libbfd-liberty-z`, instead breaking feature detection for the case when libbfd is not installed. Let's repair it.
Closes: #23

Fix Makefile error for feature-libbfd-liberty-z

---

.github/workflows/build.yaml

Use a matrix in the workflow description to build bpftool on different versions of Ubuntu (this is all the Linux runner OSes supported by GitHub at this time.

ci: Build on several OS versions

---

README.md

Fixes the link to a blog post that showcases examples and use cases
for new users of bpftool
Signed-off-by: Milan Landaverde <milan@mdaverde.com>

mirror: Update README to point to blog post of bpftool examples

---

.gitattributes

Add a .gitattributes file to the repository to enjoy correct syntax highlighting for src/Makefile.include and src/Makefile.feature in GitHub's interface.

mirror: Add .gitattributes for Makefile.* syntax highlight

---

.github/workflows/docker.yaml
Dockerfile

I often need to use bpftool on systems where it is not installed and cannot be installed. With this Dockerfile I can build and push a container image containing bpftool:
```
$ docker build -f Dockerfile -t bpftool .
```
And use it on systems without bpftool:
```
$ docker run --rm -ti --privileged --pid=host bpftool prog
```
cc @mauriciovasquezbernal

mirror: Add Dockerfile: run bpftool in a container

---

src/Makefile.feature

Feature detection for the build system, implemented specifically for the mirror repository, does not take `$(FEATURE_TESTS)` into account and simply ignores it. That variable is not necessary to run feature detection here, but on the other hand it's easier to disable some features from the Makefile if we do respect its contents. Let's skip detection for features that are not in `$(FEATURE_TESTS)`.
Fixes: 28b7cccadcce ("mirror: Reimplement feature detection and reallocarray()")

mirror: Fix Makefile.feature to account for `$(FEATURE_TESTS)`

---

.github/workflows/docker.yaml
Dockerfile

Workflows running on `pull_request_target` events run in the context of the base of the pull request, meaning that the Docker image is built from the base and not from the merge commit. This is not what we want. Revert to `pull_request` instead.
For the linter action that we used, this means that the workflow will fail when running from fork. There is a related issue on the Action's repository, but it seems to get very little activity. Let's switch to something that looks better maintained, and that does not have issues with running from forks.
Let's address the reports raised by the new linter, Hadolint.

ci: Use Hadolint linter for Dockerfile, revert workflow to pull_request

---

.github/workflows/build.yaml
.github/workflows/docker.yaml
.github/workflows/lint.yaml
.github/workflows/static-build.yaml

Only run GitHub workflow relevant to a Pull Request. For example, there is no need to rebuild bpftool on a PR that only touches the script to sync with the kernel.

ci: Add paths filter to GitHub workflows

---

.github/workflows/release.yaml

The workflow builds natively for amd64 with LLVM library and use emulation to build for arm64 with LLVM as well. The result are two static binaries with their respective compressed archives.
You can see [how the workflow acts on my fork](https://github.com/mtardy/bpftool/actions/runs/4456237417), and [how the result release page looks](https://github.com/mtardy/bpftool/releases/tag/v6.6.8) (the release has been published here, the action just creates a draft).
Honestly, GitHub action and cross-compilation/emulation (I tried both) were a bit hard to get right with the LLVM library, it took me something like 10 hours and 70 attempts + all the tests locally on amd64 and arm64.

ci: Add workflow to build and issue static binaries

---

README.md

- Add the alternative to download a compiled released version of LLVM instead of building it locally.
- Add the `-C src` and fix the LLVM_CONFIG supposed relative path.

README: fix and improve bpftool static build instructions

---

.github/workflows/build.yaml
.github/workflows/docker.yaml
.github/workflows/lint-commits.yaml
.github/workflows/lint-shell.yaml
.github/workflows/release.yaml
.github/workflows/static-build.yaml

- ci: Add concurrency groups to cancel outdated runs
- ci: Update GitHub Actions used in CI
- ci: Remove `strategy` for static builds workflow
- ci: Fix up trigger path for ShellCheck workflow

Miscellaneous clean-ups for CI

---

.github/workflows/release.yaml

Switch to a dedicated GitHub Action for packaging the source files of bpftool plus its submodules. The advantages are:
- This Action takes into account the `export-ignore` rules in `.gitattributes` files, as used by libbpf to avoid shipping the assets.
- It is to be shared with veristat's and retsnoop's release workflows, leading to less maintainance on that workflow.

ci: Use dedicated GitHub Action to package sources in release workflow

---

.github/workflows/build.yaml
.github/workflows/docker.yaml
.github/workflows/lint-shell.yaml
.github/workflows/static-build.yaml

As part of the renaming of the principal branch of the repository from `master` to `main`, update the workflow definition files to run on pushes to the `main` branch.

ci: Adjust branch names from "master" to "main"

---

src/Makefile.feature

When global variables are not initialized, the original command will get incorrect results in some versions of clang environment.
Take clang 10 as an example:
```bash
clang -v
clang version 10.0.1 (kylin 10.0.1-4.p01.ky10 119f3e344eeeca8114341787f19862d28a85f6ad)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.3.0
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
```
Not initialized (current code):
```bash
[root@localhost src]# printf '%s\n' 'struct s { int i; } __attribute__((preserve_access_index)); struct s foo;' |     clang -g -target bpf -S -o …
```

fix CLANG_BPF_CO_RE_PROBE_CMD

---

.mailmap
scripts/mailmap-update.sh

Add a script to grep for the relevant entries in the .mailmap file of the kernel repository, and use it to build a .mailmap file for the mirror repo.

mirror: Add .mailmap to the repository, sync with kernel's

---

src/Makefile.include

Hi,
I'm trying to start building the bpftool Fedora package from this repo and ran across a strange issue which prevents me from building the documentation.
After some investigation, I found that the issue is in the callable `descend` command in `Makefile.include` (which is specific to this repo) which is currently broken due to two reasons:
1. It is defined only for cases when the output is not suppressed by either `V=1` or `-s`.
2. The condition for checking the absence of `-s` is broken and it fails every time there is a variable definition containing the letter 's'.
The `descend` command is used in documentation targets and due to these errors, these targets fail to build in the following cases:
$ make V=1 doc
make: Nothing to be done for 'doc'.
$ make prefix="/usr" doc    # <- …

mirror: fix building documentation targets

---

.github/ISSUE_TEMPLATE/bug_report.md

Add an issue template to encourage users to report issues to the BPF mailing
list rather than to GitHub Issues. The GitHub issues should be used either to:
- Track issues reported to the mailing list and known to the maintainers
- Report and track issues related to the mirror itself (mirror-specific files
or modifications)
Signed-off-by: Quentin Monnet <qmo@kernel.org>

mirror: Add issue template

---

src/Makefile.feature

Feature detection from the Makefile.feature for libbfd (with the different variants of the probe) may fail on some systems where the bfd.h and dis-asm.h headers expect the `PACKAGE` or `PACKAGE_VERSION` macros [to be defined][0]. In the kernel tree, feature detection addresses it by defining the `PACKAGE` macro [when invoking the compiler][1]. Add a similar definition for the mirror repository.
Note that this issue has remained undetected for a while. This is because the bfd.h included in some distributions (Debian/Ubuntu, for example) [does not contain the inclusion guard][2].
[0]: https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=bfd/bfd-in.h;h=04e65aad5f0c235a5013513c545e57a01e96541f;hb=binutils-2_43_1#l27
[1]: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tre …

mirror: Define PACKAGE at build time when trying to detect libbfd

---

src/Makefile.feature

In commit 8a2d7d510ccd ("mirror: Fix features detection for building with clang") we prevented clang to error out when encountering unused command-line arguments in the feature probes, because we do add unused arguments for some of the probes when retrieving arguments from llvm-config, and we don't want probes to fail because of that.
At the time, the issue was apparent for the LLVM-based disassembler, so we added -Wno-unused-command-line-argument when $(LLVM) was enabled, only. We missed the case when we're building bpftool with clang instead of gcc, without building the LLVM disassembler. Let's disable the warning unconditionally instead to fix this case.
Fixes: #170

mirror: Always disable unused CLI arguments warning for feature probe

---

.github/workflows/build.yaml

Ubuntu 20.04 runners for GitHub Actions have been retired. Let's remove them from the build matrix, to avoid failures in our CI.
We want to add Ubuntu 24.04 instead, but need to finalise https://github.com/libbpf/bpftool/pull/179 for that.
Link: https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/

ci: Dump deprecated Ubuntu 20.04 runner

---

.github/dependabot.yml
.github/workflows/release.yaml

Let's try to fix the release workflow, currently broken due to outdated Actions in use, and add a dispatch trigger so we can generate the release with the right artifacts for v7.6.0.

Fix release workflow

---

README.md

Add a note in the Dependencies section to clarify that building bpftool is only supported on Linux, as discussed in issue [#193](https://github.com/libbpf/bpftool/issues/193). This helps prevent confusion for users attempting to build on unsupported platforms like macOS.

doc: clarify Linux-only build support in Dependencies section

---

.github/workflows/build.yaml

The intent of the step was that libsframe1 should be installed when
running the workflow on the ubuntu-24.04 runner. However, the condition
mistakenly checks for the step being run on the ubuntu-20.04 runner,
so it's currently a no-op. The workflow passed without this step being
run. Thus, we can assume libsframe1 was installed as a transitive
dependency in the previous step and the libsframe installation step can
be removed altogether.
Fixes: 6180da5d7191 ("ci: Add Ubuntu 24.04 runner (with ugly hack for static libbfd)")

ci: drop libsframe installation step
